app/tickets/blueprint.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import login_required, current_user
from .form import TicketCreateForm, TicketEditForm, FunctionalForm
from models import Ticket, Unit
from app import db
from flask_login import login_required

tickets = Blueprint('tickets', __name__, template_folder='templates')


@tickets.route('/', methods=['GET', 'POST'])
@login_required
def index():
    # in default tickets sorting by created date descending
    #FIXME need to filter function 
    order_method = Ticket.created.desc()
    if request.form.get('newest', False):
        order_method = Ticket.created.desc()
    if request.form.get('older', False):
        order_method = Ticket.created.asc()
        print(Ticket.in_work.desc())
    if request.form.get('by_status', False):
        order_method = Ticket.in_work.asc()
    tickets_list = Ticket.query.order_by(order_method).all()

    # show just user.unit tickets
    if request.form.get('user_unit', False):
        user_unit = Unit.query.filter_by(name=current_user.unit.name).first()
        tickets_list = Ticket.query.filter_by(unit=user_unit).all()
    return render_template('tickets/index.html', tickets_list=tickets_list, count=len(tickets_list))


@tickets.route('/<slug>', methods=['POST', 'GET'])
@login_required
def ticket_item(slug):
    ticket = Ticket.query.filter_by(slug=slug).first()
    func_form = FunctionalForm()
    if request.form.get('assign', False):
        ticket.in_work_by_user = current_user.username
        ticket.in_work = '1'
        db.session.add(ticket)
        db.session.commit()
    if request.form.get('done', False):
        ticket.in_work = '2'
        db.session.add(ticket)
        db.session.commit()
        return redirect(url_for('users.cabinet', username=current_user.username))
    return render_template('tickets/ticket.html', ticket=ticket, form=func_form)


@tickets.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = TicketCreateForm()

    if form.validate_on_submit():
        header = form.header.data
        unit = Unit.query.filter_by(name=form.unit.data).first()
        description = form.description.data
        check_task = Ticket.query.filter_by(name=header).first()
        if check_task is None:
            ticket = Ticket(name=header, 
                            unit=unit, 
                            description=description, 
                            who_create=current_user.username,
                            in_work='0')
            db.create_all()
            db.session.add(ticket)
            db.session.commit()
            return redirect(url_for('tickets.index'))
    return render_template('tickets/create.html', form=form)


@tickets.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_ticket(slug):
    form = TicketEditForm()
    ticket = Ticket.query.filter_by(slug=slug).first()
    if form.validate_on_submit():
        ticket.name = form.header.data
        ticket.unit = Unit.query.filter_by(name=form.unit.data).first()
        ticket.description = form.description.data
        db.session.add(ticket)
        db.session.commit()
        return redirect(url_for('tickets.ticket_item', slug=slug))
    elif request.method == 'GET':
        form.header.data = ticket.name
        form.unit.data = ticket.unit
        form.description.data = ticket.description
    return render_template('tickets/edit.html', form=form)

app/tickets/templates/tickets/create.html
{%extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{%block title%} Create task {%endblock%}

{%block content%}
<div class="containet text-center">
    <div class="row">
        <div class="col-lg-12">
            <h1>
                Create new task
            </h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            {{wtf.quick_form(form)}}
            {% for message in get_flashed_messages() %}
                {{ message }}
            {% endfor %}
        </div>
    </div>
</div>

{%endblock%}

app/tickets/templates/tickets/edit.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}


{% block title %} Edit ticket {% endblock %}

{% block content %}

<div>
    <h1>Edit ticket</h1>
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/tickets/templates/tickets/index.html
{%extends 'base.html'%}
{% block head %}
    <style type="text/css">
        table{
            border: 2px solid black;
            padding: 3px;
            margin: 10px;
            width: 70%;
        }
        th, tr, td{
            border: 2px dotted grey;
            padding: 1px;
        }

    </style>
{% endblock %}
{%block title%} Tickets {%endblock%}

{%block content%}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Tasks</h1>
            </div>
        </div>
        {% if count < 1 %}
        <div class="row">
            <div class="col-lg-12">
                <h2>No available tickets</h2>
                <a href="{{url_for('tickets.create')}}"><button type="button" class="btn btn-success">Create one</button></a>
            </div>
        </div>
        {% else %}
        <div class="col-lg-12 sort" style="float:left;">
            <p>Sort by</p>
            <form action="{{url_for('tickets.index')}}" method="POST">
                <input type="submit" value="Newest" name="newest">
                <input type="submit" value="Older" name="older">
                <input type="submit" value="For my unit" name="user_unit">
                <input type="submit" value="By status" name="by_status">
            </form>
        </div>
        <div class="row">
            <div class="col-lg-12">
            <table>
                <thead>
                    <th>Ticket</th>
                    <th>Created by</th>
                    <th>Date</th>
                    <th>Assigned to</th>
                    <th>Status</th>
                </thead>
                <tbody>
                {%for ticket in tickets_list%}
                    <tr>
                            <td class="ticket-name">
                                <a class="nav-link" href="{{url_for('tickets.ticket_item', slug = ticket.slug)}}">{{ ticket.name }}</a>
                            </td>
                            <td>{{ ticket.who_create }}</td>
                            <td>
                                {{ ticket.created.strftime('%m.%d.%Y %H:%M:%S') }}
                            </td>
                            <td>{{ticket.unit.name}}</td>
                                {% if ticket.in_work == '0' %}
                            <td><span style="color:red;">Awaiting for preformer</span>
                            </td>
                                {% elif ticket.in_work == '1' %}
                            <td><span style="color: green">In work by: {{ticket.in_work_by_user}}</span>
                            </td>
                                {% elif ticket.in_work == '2' %}
                                <td><span style="color: brown">Done by user: {{ticket.in_work_by_user}}</span>
                                {% endif %}
                            
                    </tr>
                    
                </tbody>
                {%endfor%}
            </table>
            </div>
            
        {% endif %}
    </div>

{%endblock%}

app/tickets/templates/tickets/ticket.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{%block title%}
{{ ticket.name }}
{%endblock%}

{%block content%}

<div class="container">
    <div class="row">
        <div class="col-md-4 text-left">
            <h1>{{ticket.name}}</h1>
            <p>
                {{ticket.description}}
            </p>
            <p>Unit assigned: {{ticket.unit.name}}</p>
            <p>Task created by: {{ticket.who_create}}</p>
            {% if ticket.in_work == '1' %}
                <p style="color: green;">In work: {{ticket.in_work_by_user}}</p>
                    <form action="{{url_for('tickets.ticket_item', slug=ticket.slug)}}" method="POST">
                        <input type="submit" name="done" value="Done">
                    </form>
            {% elif ticket.in_work == '0' %}
                <p style="color: red;">Await for accept</p>
                {% if current_user.unit.name == ticket.unit.name %}
                    <form action="{{url_for('tickets.ticket_item', slug=ticket.slug)}}" method="POST">
                        <input type="submit" name="assign" value="assign">
                    </form>
                {% endif %}
            {% elif ticket.in_work == '2' %}
                    <p style="color: brown;">Solved!</p>
            {% endif %}
        </div>
        {% if current_user.username == ticket.who_create %}
        <div class="col-md-4 text-left" style="margin-top:10px;">
            <h2>Manage: </h2>
            <form action="" role="form" method="post">
                {{form.delete}}
            </form>
            <a href="{{url_for('tickets.edit_ticket', slug=ticket.slug)}}"><button type="button" class="btn btn-warning">Edit</button></a>
            {% for message in get_flashed_messages() %}
                <div class="alert alert-danger">
                    {{message}} <a href="url_for"></a>
                </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{%endblock%}

app/tickets/templates/tickets/ticket_item.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{%block title%}
{{ ticket.name }}
{%endblock%}

{%block content%}

<div class="container">
    <div class="row">
        <div class="col-lg-6 text-left">
            <h1>
                {{ticket.name}}
            </h1>
            <h2>Unit on work: {{ticket.unit.name}}</h2>
            <p>
                {{ticket.description}}
            </p>
            <p>Task created by: {{ticket.who_create}}</p>


        </div>
        <div class="col-lg-6 text-left" style="margin-top:10px;">
            <h2>Operations: </h2>
            <form action="" role="form" method="post">
            {{ form.delete }}
            </form>
            {% for message in get_flashed_messages() %}
                <div class="alert alert-danger">
                    {{message}} <a href="url_for"></a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{%endblock%}