app/users/blueprint.py
from flask import Blueprint, render_template, abort, redirect, url_for, request
from flask_login import current_user
from models import User, Ticket, Unit
from .form import EditProfileForm
from app import db
from flask_login import login_required
users = Blueprint('users', __name__, template_folder='templates')


@users.route('/')
@login_required
def index():
    users = User.query.all()
    return render_template('users/index.html', users=users)


@users.route('/<username>', methods=['GET', 'POST'])
@login_required
def user_profile(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('users/user_profile.html', user=user)


@users.route('/edit-profile/<username>', methods=['GET', 'POST'])
@login_required
def edit_profile(username):
    form = EditProfileForm()
    user = User.query.filter_by(username=username).first()
    if form.validate_on_submit():
        user.real_name = form.real_name.data
        user.phone = form.phone.data
        user.about = form.about.data
        user.email = form.email.data
        user.unit = Unit.query.filter_by(name=form.unit.data).first()
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.cabinet', username=username))
    elif request.method == 'GET':
        form.real_name.data = user.real_name
        form.phone.data = (user.phone or 'None')
        form.about.data = (user.about or 'None')
        form.email.data = (user.email)
    return render_template('users/edit_profile.html', form=form)


@login_required
@users.route('/cabinet/<username>')
def cabinet(username):
    if username != current_user.username:
        abort(403)
    ticket_list = Ticket.query.filter_by(in_work_by_user=current_user.username).all()
    return render_template('users/cabinet.html', username=username, ticket_list=ticket_list)

app/users/templates/users/cabinet.html
{% extends 'base.html' %}

{%block title%} {{usename}} {% endblock %}
{% block head %} 
<style type="text/css">
    table{
        border: 2px solid black;
        padding: 3px;
        margin: 10px;
        width: 70%;
    }
    th, tr, td{
        border: 2px dotted grey;
        padding: 1px;
    }

    .ticket-name {
        width: 40%;
    }

</style>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 15px;">
    <div class="row">
        <div class="col-md-4 cabinet-head">
            <h2>Hello {{username}}</h2>
        </div>
    </div>

        <div class="col-lg-12 cabinet-body">
            <!--p>My tickets: </p>
            {% for ticket in ticket_list %}
            {% if ticket.in_work == '1' %}
            <div class="ticket">
                <a href="{{url_for('tickets.ticket_item', slug=ticket.slug)}}" class="">
                    {{ticket.name}}
                </a>
            {% elif ticket.in_work == '2'%}
            <a href="{{url_for('tickets.ticket_item', slug=ticket.slug)}}" class="">
                {{ticket.name}}
            </a>
            {% endif %}
            {% endfor %} -->
            <div class="last-tickets">
            <h4>Last tickets</h4>
            <table>
                <thead>
                    <th>Name</th>
                    <th>From user</th>
                    <th>Date</th>
                </thead>
                <tbody>
                    {% for ticket in ticket_list %}
                    {% if ticket.in_work == '1' %}
                    <tr>
                        <td class="ticket-name"><a href="{{url_for('tickets.ticket_item', slug=ticket.slug)}}">{{ticket.name}}</a></td>
                        <td>{{ ticket.who_create }}</td>
                        <td>{{ ticket.created }}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
              
                {% if ticket_list == [] %}
                    <tr><td class>No unsolved tickets. Check the <a href="{{url_for('tickets.index')}}">Tickets</a> page</td></tr>
                {% endif %}
            </tbody>
            </table>
            </div>
            <div class="solved">
                <h4>Solved tickets</h4>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>From user</th>
                        <th>Date</th>
                    </thead>
                    <tbody>
                        {% for ticket in ticket_list %}
                        {% if ticket.in_work == '2' %}
                        <tr>
                            <td class="ticket-name"><a href="{{url_for('tickets.ticket_item', slug=ticket.slug)}}">{{ticket.name}}</a></td>
                            <td>{{ ticket.who_create }}</td>
                            <td>{{ ticket.created }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
        
    <div class="col-md-4 cabinet-footer">
        <a href="{{url_for('users.edit_profile', username=username)}}"><button type="button" class="btn btn-info">Edit profile</button>
        </a>
    </div>
</div>
{% endblock %}

app/users/templates/users/edit_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} Edit profile {% endblock %}

{% block content %}

<div class="col-md-6">
    {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/users/templates/users/index.html
{% extends 'base.html' %}

{% block title %} Пользователи {% endblock %}

{% block content %}

    <h1>Registered users</h1>

    {% for user in users %}

    <p><a href="{{url_for('users.user_profile', username=user.username)}}">{{user.username}} Unit: {{ user.unit.name }}</a></p>

    {% endfor %}

{% endblock %}

app/users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}

{% block content %}
<div>
    <h2>{{ user.username }}</h2>
    <div>
        <p><h6 style="color: blue;">Username: </h6>{{user.username}}</p>
        <p><h6 style="color: blue;">Name: </h6>{{user.real_name}}</p>
        <p><h6 style="color: blue;">Email: </h6>{{user.email}}</p>
        <p><h6 style="color: blue;">Phone: </h6>{{user.phone}}</p>
        <p><h6 style="color: blue;">Unit: </h6>{{user.unit.name}}</p>
        <p><h6 style="color: blue;">About: </h6>{{user.about}}</p>
    </div>

</div>
    {% if current_user.username == user.username %}

        <a href="{{url_for('users.edit_profile', username=user.username)}}"><button type="button" class="btn btn-info">Edit
        </button></a>
    {% endif %}
{% endblock %}