app/tickets/blueprint.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import login_required, current_user
from .form import TicketCreateForm, TicketEditForm, FunctionalForm
from models import Ticket, Unit
from app import db
from flask_login import login_required

tickets = Blueprint('tickets', __name__, template_folder='templates')


@tickets.route('/', methods=['GET', 'POST'])
@login_required
def index():
    # in default tickets sorting by created date descending
    #FIXME need to filter function 
    order_method = Ticket.created.desc()
    if request.form.get('newest', False):
        order_method = Ticket.created.desc()
    if request.form.get('older', False):
        order_method = Ticket.created.asc()
        print(Ticket.in_work.desc())
    if request.form.get('by_status', False):
        order_method = Ticket.in_work.asc()
    tickets_list = Ticket.query.order_by(order_method).all()

    # show just user.unit tickets
    if request.form.get('user_unit', False):
        user_unit = Unit.query.filter_by(name=current_user.unit.name).first()
        tickets_list = Ticket.query.filter_by(unit=user_unit).all()
    return render_template('tickets/index.html', tickets_list=tickets_list, count=len(tickets_list))


@tickets.route('/<slug>', methods=['POST', 'GET'])
@login_required
def ticket_item(slug):
    ticket = Ticket.query.filter_by(slug=slug).first()
    func_form = FunctionalForm()
    if request.form.get('assign', False):
        ticket.in_work_by_user = current_user.username
        ticket.in_work = '1'
        db.session.add(ticket)
        db.session.commit()
    if request.form.get('done', False):
        ticket.in_work = '2'
        db.session.add(ticket)
        db.session.commit()
        return redirect(url_for('users.cabinet', username=current_user.username))
    return render_template('tickets/ticket.html', ticket=ticket, form=func_form)


@tickets.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = TicketCreateForm()

    if form.validate_on_submit():
        header = form.header.data
        unit = Unit.query.filter_by(name=form.unit.data).first()
        description = form.description.data
        check_task = Ticket.query.filter_by(name=header).first()
        if check_task is None:
            ticket = Ticket(name=header, 
                            unit=unit, 
                            description=description, 
                            who_create=current_user.username,
                            in_work='0')
            db.create_all()
            db.session.add(ticket)
            db.session.commit()
            return redirect(url_for('tickets.index'))
    return render_template('tickets/create.html', form=form)


@tickets.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_ticket(slug):
    form = TicketEditForm()
    ticket = Ticket.query.filter_by(slug=slug).first()
    if form.validate_on_submit():
        ticket.name = form.header.data
        ticket.unit = Unit.query.filter_by(name=form.unit.data).first()
        ticket.description = form.description.data
        db.session.add(ticket)
        db.session.commit()
        return redirect(url_for('tickets.ticket_item', slug=slug))
    elif request.method == 'GET':
        form.header.data = ticket.name
        form.unit.data = ticket.unit
        form.description.data = ticket.description
    return render_template('tickets/edit.html', form=form)

app/users/blueprint.py
from flask import Blueprint, render_template, abort, redirect, url_for, request
from flask_login import current_user
from models import User, Ticket, Unit
from .form import EditProfileForm
from app import db
from flask_login import login_required
users = Blueprint('users', __name__, template_folder='templates')


@users.route('/')
@login_required
def index():
    users = User.query.all()
    return render_template('users/index.html', users=users)


@users.route('/<username>', methods=['GET', 'POST'])
@login_required
def user_profile(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    return render_template('users/user_profile.html', user=user)


@users.route('/edit-profile/<username>', methods=['GET', 'POST'])
@login_required
def edit_profile(username):
    form = EditProfileForm()
    user = User.query.filter_by(username=username).first()
    if form.validate_on_submit():
        user.real_name = form.real_name.data
        user.phone = form.phone.data
        user.about = form.about.data
        user.email = form.email.data
        user.unit = Unit.query.filter_by(name=form.unit.data).first()
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.cabinet', username=username))
    elif request.method == 'GET':
        form.real_name.data = user.real_name
        form.phone.data = (user.phone or 'None')
        form.about.data = (user.about or 'None')
        form.email.data = (user.email)
    return render_template('users/edit_profile.html', form=form)


@login_required
@users.route('/cabinet/<username>')
def cabinet(username):
    if username != current_user.username:
        abort(403)
    ticket_list = Ticket.query.filter_by(in_work_by_user=current_user.username).all()
    return render_template('users/cabinet.html', username=username, ticket_list=ticket_list)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%} {%endblock%} | HelpDesk</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block head %}{% endblock %}
</head>
<body>
<!-- header -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{url_for('index')}}">HelpDesk</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('index')}}">Home</a>      
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('users.cabinet', username=current_user.username)}}">My cabinet</a>      
      </li>
      <li class="nav-item active">
      <a class="nav-link" href="{{url_for('tickets.create')}}">Create new task</a>
      </li>
      <li class="nav-item active"><a class="nav-link" href="{{url_for('users.index')}}">Users</a></li>
    </ul>
      <ul>
          {% if current_user.username %}
        <a href="{{url_for('auth.logout')}}" class="nav-link">{{current_user.username}} LogOut</a>
        {% else %}
        <a href="{{url_for('auth.login')}}" class="nav-item active nav-link">LogIn</a>
        {% endif %}
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

    </form>
  </div>
</nav>

<!-- page content -->
{% block content %} {% endblock %}
</body>
</html>

app/templates/index.html
{%extends 'base.html'%}

{%block title%} Главная {%endblock%}

{%block content%}

<div class="container">
    <div class="row">
        <div class="col-lg-6 text center">
        {% if current_user.username %}
            <p>News and bla bla bla</p>                
        {% else %}
            <h1>Hello Stranger!</h1>
            <h3>You must be logged in for use services</h3>
            <a class="nav-link" href="{{url_for('auth.login')}}">
                <button type="button" class="btn btn-success">Login</button>
                </a>
        {% endif %}
        </div>
        </div>
    <h6>HelpDesk by Tony Prilipa</h6>
    </div>



{%endblock%}